### ISSUE TITLE
[Back-end] 日志中remote-addr输出均为127.0.0.1

### ISSUE THREAD

**Issue by Gnnng** [pollow/Contacts#39]
应当是端口转发的时候，没有配好，这个似乎不是我们能解决的

**Comment by MForever78** [comment]
本地测试通过了的，结果线上看了一下还是输出 127.0.0.1。我再查一下

**Comment by Gnnng** [comment]
可能是反向代理的问题，我们前面是不是有个nginx

在 6/5/15 12:07 PM, Tong Xingang 写道:
>
> Reopened #39 <https://github.com/pollow/Contacts/issues/39>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pollow/Contacts/issues/39#event-323194602>.
>

-- 
Gong Deli
Junior
College of Computer Science and Technology
Zhejiang University

**Comment by MForever78** [comment]
前面有一个 Apache，但我就是来解决这个问题的。改了以后应该会用 X-Forward-For 来读取 ip 了才对

发送自 Outlook

    _____________________________

**Comment by MForever78** [comment]
服务器上跑的的是 apache 2.2.14

根据文档 `mod_proxy_http` 应该会加上 `X-Forwarded-*` 三个 header ，但是抓包显示并没有。

文档在：http://httpd.apache.org/docs/2.2/mod/mod_proxy.html#x-headers

抓包结果是：（部分信息隐去）

```
GET / HTTP/1.1
Host: localhost:3000
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36
DNT: 1
Accept-Encoding: gzip, deflate, sdch
Accept-Language: zh-CN,zh;q=0.8,en;q=0.6,zh-TW;q=0.4
Cookie: ******
If-None-Match: ******
Via: 1.1 ******
Connection: Keep-Alive
``` 

判断可能为 Apache 版本太低。因为服务器上跑了太多其他东西，Apache 升级有不向后兼容的地方，所以不修复了。
